Refactor circle config to separate out docker push (#92)
* Refactor circle config to separate out docker push

* Edited workflow

* Added image version check

* Removed original version match from circle build

* Exit if docker creads not found

* Update .circleci/config.yml

Co-authored-by: Viswajith Venugopal <viswajithiii@gmail.com>

* Update .circleci/config.yml

Co-authored-by: Viswajith Venugopal <viswajithiii@gmail.com>

* Update .circleci/config.yml

Co-authored-by: Viswajith Venugopal <viswajithiii@gmail.com>

* Update .circleci/config.yml

Co-authored-by: Viswajith Venugopal <viswajithiii@gmail.com>

* Update .circleci/config.yml

* Add execution permission

* Fix check run step order

* Added status check after check to run step

Co-authored-by: Viswajith Venugopal <viswajithiii@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,42 +41,13 @@ jobs:
     executor: custom
     steps:
     - checkout
-    - setup_remote_docker
 
     - run:
-        name: Build binaries and image
+        name: Build binaries
         command: |
-          make build image
+          make build
 
-    - run:
-        name: Ensure `kube-linter version` returns the expected value.
-        command: |
-          expected_version="$(./get-tag)"
-          version_from_binary="$(.gobin/kube-linter version)"
-          version_from_image="$(docker run "stackrox/kube-linter:${expected_version}" version)"
-          echo "Version from kube-linter binary: ${version_from_binary}. From image: ${version_from_image}. Expected version: ${expected_version}"
-          [[ "${version_from_binary}" == "${expected_version}" ]]
-          [[ "${version_from_image}" == "${expected_version}" ]]
-
-    - run:
-        name: Push image to DockerHub, if applicable.
-        command: |
-          if [[ -z "${DOCKER_IO_PUSH_USERNAME}" && -z "${DOCKER_IO_PUSH_PASSWORD}" ]]; then
-            if [[ "${CIRCLE_BRANCH}" == "main" || -n "${CIRCLE_TAG}" ]]; then
-              echo "DockerHub creds not found. This is unexpected if the push is to main or if a tag has been pushed."
-              exit 1
-            fi
-            echo "DockerHub creds not found, not pushing."
-            exit 0
-          fi
-          docker login -u "$DOCKER_IO_PUSH_USERNAME" -p "$DOCKER_IO_PUSH_PASSWORD"
-          img="stackrox/kube-linter:$(./get-tag)"
-          docker push "${img}"
-
-          if [[ -n "${CIRCLE_TAG}" ]]; then
-            docker tag "${img}" stackrox/kube-linter:latest
-            docker push stackrox/kube-linter:latest
-          fi
+    - check-binary-version-match
 
     - run:
         name: Create a GitHub release, if on tag.
@@ -111,6 +82,82 @@ jobs:
           name: Run E2E tests
           command: |
             make e2e-test
+  
+  image:
+    executor: custom
+    steps:
+    - checkout
+    - check-label-to-run:
+        label: push-docker-image 
+    - setup_remote_docker
+    
+    - run:
+        name: Build image
+        command: |
+          make image
+
+    - check-binary-version-match
+    - check-image-version-match
+
+    - run:
+        name: Push image to DockerHub, if applicable.
+        command: |
+          if [[ -z "${DOCKER_IO_PUSH_USERNAME}" && -z "${DOCKER_IO_PUSH_PASSWORD}" ]]; then
+            echo "DockerHub creds not found. This is unexpected and hence not pushing."
+            exit 1
+          fi
+          docker login -u "$DOCKER_IO_PUSH_USERNAME" -p "$DOCKER_IO_PUSH_PASSWORD"
+          img="stackrox/kube-linter:$(./get-tag)"
+          docker push "${img}"
+
+          if [[ -n "${CIRCLE_TAG}" ]]; then
+            docker tag "${img}" stackrox/kube-linter:latest
+            docker push stackrox/kube-linter:latest
+          fi
+
+commands:
+  check-label-to-run:
+    description: Run on main or tags, but skip on PRs unless the given label is provided
+    parameters:
+      label:
+        type: string
+    steps:
+      - run:
+          name: Determine whether to run step
+          command: |
+            set +e
+            if [[ "${CIRCLE_BRANCH}" == "main" || -n "${CIRCLE_TAG}" ]]; then
+              echo "On main or tag, running the step"
+            else
+              .circleci/pr_has_label.sh "<< parameters.label >>"
+              if [[ $? -eq 1 ]]; then
+                echo "Skipping step because we're on a PR. Apply the << parameters.label >> label to your PR if you want to run them."
+                circleci step halt
+              fi
+              [[ $? -eq 0 ]]
+            fi
+
+  check-binary-version-match:
+    description: Check the built binary matches with the expected version
+    steps:
+      - run:
+          name: Verify the binary version
+          command: |
+            expected_version="$(./get-tag)"
+            version_from_binary="$(.gobin/kube-linter version)"
+            echo "Version from kube-linter binary: ${version_from_binary}. Expected version: ${expected_version}"
+            [[ "${version_from_binary}" == "${expected_version}" ]]
+  
+  check-image-version-match:
+    description: Check the built image matches with the expected version
+    steps:
+      - run:
+          name: Verify the image version
+          command: |
+            expected_version="$(./get-tag)"
+            version_from_image="$(docker run "stackrox/kube-linter:${expected_version}" version)"
+            echo "Version from image: ${version_from_image}. Expected version: ${expected_version}"
+            [[ "${version_from_image}" == "${expected_version}" ]]
 
 workflows:
   version: 2
@@ -122,8 +169,10 @@ workflows:
         <<: *runOnAllTags
     - build:
         <<: *runOnAllTags
-        context: docker-io-push
     - e2e-test:
         <<: *runOnAllTags
         requires:
           - build
+    - image:
+        <<: *runOnAllTags
+        context: docker-io-push
